### ISSUE TITLE
Users should be able to use #hashtags and @usernames in forum posts and tweets

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#125]
hashtags and usernames should autocomplete

**Comment by walkeriniraq** [comment]
The indexing is working well - need to implement a page to view the hashtags, then I can close this.

**Comment by tasermonkey** [comment]
@walkeriniraq is there an easy way to get hashtags and auto-complete to work within the post text boxes too?  Like in github(or twitter) you type "(at)kv" it would popup a small dropdown with "kvort" in it.  I know that is probably just a #wishlist thing but if it easy, I think that will go along way to making this app that much more awesome.

**Comment by walkeriniraq** [comment]
Did it last year. Getting a div positioned at the cursor was tweaky but
possible. Feel free to put it on the wish list.
