### ISSUE TITLE
long urls cause the page to scroll horizontally under iOS / chrome

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#147]
Might be a problem with long words as well. Might use some sort of URL rewriter?

**Comment by walkeriniraq** [comment]
Neat - I didn't know that was a thing.

**Comment by Wingar** [comment]
It's a CSS3 thing, not sure how old devices will deal with it.

**Comment by walkeriniraq** [comment]
Probably just wouldn't support it, which means it's still an improvement
since I wasn't going to fix it at all.  :)
