### ISSUE TITLE
Discussion: Notifications of mentions

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#150]
Before I started to implement something for notifications... I noticed you had written this in the JCCC forums:
> "I had notifications for updates to posts, but it was WAY too noisy and I yanked it out before the cruise. Trust me, no post notifications was better than the way it was. Will fix for next year."

I was thinking for like (at)mentions notifications we would just keep a count, say like, "You have been mentioned in n-number of tweets, since the last time you refreshed" (or something along those lines).

This way its not flooding the user with information, then they can just view a page that shows all of their mentions (the API link is `/api/v2/stream/m/username`).   Then it would reset the count back to 0.

Would that be a good in between?

**Comment by walkeriniraq** [comment]
This is also working well
