### ISSUE TITLE
display unread seamails on the header bar

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#162]
The UI could hit the endpoint: /api/v2/user/new_seamail
to get back: 
{
status: "ok",
email_count: 2
}
Maybe have something look like this(though look better than this):
![screenshot 2014-12-28 21 55 23](https://cloud.githubusercontent.com/assets/284844/5565895/d181268a-8edc-11e4-88b1-67c011b6acb8.png)

**Comment by walkeriniraq** [comment]
This is working!!!
