### ISSUE TITLE
Profile needs some styling work

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#169]

**Comment by Wingar** [comment]
How's this look? And yes, it scales perfectly to mobile. Columns, yo. :)
![image](https://cloud.githubusercontent.com/assets/1838015/5771572/f87a15a6-9d93-11e4-8673-e74baddb3d58.png)
I also changed around the user profile page a bit too, it similarly uses columns.
![image](https://cloud.githubusercontent.com/assets/1838015/5771577/1f212190-9d94-11e4-92e8-ea78e3b6f20c.png)
