### ISSUE TITLE
Main tweets page is slow

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#176]
Takes 1-2 seconds to reload - try using the chrome profiling to improve performance

**Comment by walkeriniraq** [comment]
Added image caching to try and alleviate the problem - significantly helps performance but the pages are still slow. More work to be done.

**Comment by tasermonkey** [comment]
What counts as slow, I think my nexus 4 it was fine.  It might take like a second or so, but to me its mostly the flash on the screen that bothers me.

**Comment by walkeriniraq** [comment]
I'm worried that on slower devices that 1-2 seconds will be 10-20.

**Comment by tasermonkey** [comment]
Though curious if the main slowdown on the ship will be the network?
