### ISSUE TITLE
user auth failure

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#177]
When I try to GET `http://cm.raccoonfink.com/api/v2/user/auth?password=XXXX&username=rangerrick` I get the following error:

```
Started GET "/api/v2/user/auth?password=[FILTERED]&username=rangerrick" for 98.101.157.50 at 2015-01-05 17:33:10 +0000
Processing by API::V2::UserController#auth as HTML
  Parameters: {"password"=>"[FILTERED]", "username"=>"rangerrick"}
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 35.0000ms
  MOPED: 127.0.0.1:27017 QUERY        database=development collection=users selector={"$query"=>{"un"=>"rangerrick"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 3.0000ms
Completed 500 Internal Server Error in 197ms

NameError (uninitialized constant UserController::ACTIVE_STATUS):
  app/controllers/application_controller.rb:43:in `validate_login'
  app/controllers/api/v2/user_controller.rb:5:in `auth'
```

**Comment by walkeriniraq** [comment]
I'm beginning to be sorry that I moved that damned constant.

I'll fix it when I get home from work if James doesn't get it first.

**Comment by walkeriniraq** [comment]
Or you'll just fix it yourself.  :)

**Comment by RangerRick** [comment]
:)

I can't remember, did you ever give me commit access?  I'd be happy to do this kind of quick-fix directly if you want.  I don't mind doing it with pull requests either though.  Whatever you're comfortable with.

**Comment by walkeriniraq** [comment]
I don't remember. I merged your commit already, in any case.
