### ISSUE TITLE
User display should show a larger version of the profile photo.

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#180]

**Comment by tasermonkey** [comment]
https://github.com/walkeriniraq/twitarr/commit/371fe21eabd5b60ff44639fe3b454822a2eda6cc now keeps the original version... Should I downsize the photo any though?  Right now its just the original size image.

**Comment by tasermonkey** [comment]
And this https://github.com/walkeriniraq/twitarr/commit/545713799fb59d1bd368592811a944b53095330e allows the UI to get the full photo at: /api/v2/user/:user?full=true

**Comment by walkeriniraq** [comment]
I can't imagine we'll want it too big - my vision for the profile page is
something like the facebook profile - a bigger picture of the user and some
details if they want them, like hometown, etc.

**Comment by tasermonkey** [comment]
alright, 384px is what twitter does... Is that a good enough arbitrary number?

**Comment by walkeriniraq** [comment]
This is working - I tweaked the sizes a bit but otherwise I think it's good.
