### ISSUE TITLE
HTML-based injection of text

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#186]
We are currently vulnerable to html and js injection, since the text is passed straight from the database into the html form...

I would like people to be able to post links, and use carriage returns in text, but we need to close this loophole.

**Comment by walkeriniraq** [comment]
I'm seriously considering "marking up" the html on the client side with links and <br /> - it's the only way to completely avoid injection.

**Comment by Wingar** [comment]
Why not just use CGI.escapeHTML?

**Comment by walkeriniraq** [comment]
Hmm - I was thinking that it'd interfere with the html added by the twitter
package, but really it's just a question of escaping the HTML *before* adding
the twitter enrichment.

Good call.

**Comment by Wingar** [comment]
Seems to work just fine on StreamPost.create
![image](https://cloud.githubusercontent.com/assets/1838015/5623243/3e32f448-95a4-11e4-9b2d-2f61b5c06c43.png)
