### ISSUE TITLE
Users could write tweets that are hundreds of lines long.

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#195]
Not too worried about this in forums or in seamail, but it would completely ruin the flow of the tweets page. Since @tasermonkey has already put in the tweet detail page, it should be pretty easy to just limit the size of a tweet and put a "more" link at the bottom that takes the user to the details.

**Comment by tasermonkey** [comment]
Would we want to have the backend return only say the first 140 characters on the mean page?  Or just have the client side thin it out. Might make the tweet page load faster, if there are fewer characters per tweet.

**Comment by Wingar** [comment]
![image](https://cloud.githubusercontent.com/assets/1838015/5753325/5fe73ebc-9cdb-11e4-8abd-b42046fe6a28.png)
![image](https://cloud.githubusercontent.com/assets/1838015/5753331/70708180-9cdb-11e4-9164-b55b26a8cc3e.png)
How does this look?

**Comment by walkeriniraq** [comment]
Nice.

**Comment by Wingar** [comment]
Well, I'll push it up now.
It's slightly messy but it's all done within the decorator on .to_hash. It uses a new item in the options hash, length_limit, which is currently set to 140 on the stream view. As long as the option key is empty it wont do anything.
