### ISSUE TITLE
GET /api/v2/user/view/:username fails without logging in

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#201]
I'm trying to implement read-only twitarr timeline in CruiseMonkey, but I can't get the info to turn usernames in the timeline into actual names.  I can see why you might not expose the full profile by default in a read-only mode, but it would be nice to at least have a call to determine the user's profile name associated with their username...

**Comment by walkeriniraq** [comment]
Just pushed a fix. I also have it return the same response for admin or
non-admin users.
