### ISSUE TITLE
API calls do not honor the key=XXX param

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#208]
It appears that `401 Unauthorized` is being returned even if a valid key is passed as a parameter.

```
curl -L -o - 'http://cm.raccoonfink.com/api/v2/user/auth?username=rangerrick&password=XXXXXXXX'
{"status":"ok","key":"rangerrick:12345"}
```

```
curl --verbose -L -o - 'http://cm.raccoonfink.com/api/v2/alerts/check?key=rangerrick:12345'
* Hostname was NOT found in DNS cache
*   Trying 69.174.246.178...
* Connected to cm.raccoonfink.com (69.174.246.178) port 80 (#0)
> GET /api/v2/alerts/check?key=rangerrick:12345 HTTP/1.1
> User-Agent: curl/7.37.1
> Host: cm.raccoonfink.com
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Date: Tue, 13 Jan 2015 00:56:43 GMT
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Content-Type: text/html
< Cache-Control: no-cache
< X-Request-Id: dc2854b6-1e3f-4cab-ba73-282c27813bfc
< X-Runtime: 0.077000
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Authorization,Content-Type
< Access-Control-Allow-Methods: OPTIONS,GET,POST,PUT,DELETE
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
* Connection #0 to host cm.raccoonfink.com left intact
```

I also tried with a manual call to `/api/v2/user/new_seamail` which I used last year with success so it's a change in behavior since last year.

**Comment by RangerRick** [comment]
Looks like at some point things got refactored.  It appears that application_controller.rb has a "valid_key" def but nothing calls it.  I can't figure out how it's supposed to be wired up, though.

**Comment by tasermonkey** [comment]
Though I can bring it back, won't it be easy enough for you to just use the more secured cookie method?

**Comment by tasermonkey** [comment]
Well, in the sake of time, I added it back in: https://github.com/walkeriniraq/twitarr/commit/9fd75cb5848f65c45d8fd26d57511ad2239e4286

**Comment by RangerRick** [comment]
For the sake of posterity, you can't use cookies with ajax calls when using an allowed origin of '*' so passing the key is better.  The alternative would be to pass it as a header, and change the CORS stuff to explicitly allow that header.  (ie, X-Twitarr-Key: XXXXX)

**Comment by tasermonkey** [comment]
Yep, I didn't realize that the CORS stuff is so damn picky!
