### ISSUE TITLE
Add a "started by" section to the forums meta

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#209]

**Comment by tasermonkey** [comment]
like the author?

**Comment by walkeriniraq** [comment]
Author of first post

**Comment by tasermonkey** [comment]
https://github.com/walkeriniraq/twitarr/commit/d9f741350f9f944f49fce16fd2323fd38a0b33de fixes this

**Comment by walkeriniraq** [comment]
Display name?  :)

**Comment by tasermonkey** [comment]
So picky... Here it is: https://github.com/walkeriniraq/twitarr/commit/1df3a1286fa2c432892def34f123d4af0f3e2c58

{
forum_meta: [
{
id: "54ab57cb6313b17290000031",
subject: "Food pictures are awesome",
created_by: "james",
created_by_display_name: "james",
posts: "3 posts",
timestamp: "2015-01-04T13:22:00.000Z"
},
{
id: "54ab57cb6313b1729000002e",
subject: "First forum",
created_by: "kvort",
created_by_display_name: "picky nate",
posts: "2 posts",
timestamp: "2015-01-04T13:15:00.000Z"
}
]
}

**Comment by walkeriniraq** [comment]
Thanks.
