### ISSUE TITLE
The check for the base password is failing since user.change_password route no longer exists

### ISSUE THREAD

**Issue by walkeriniraq** [walkeriniraq/twitarr#210]
Need to adjust to new logic

**Comment by Wingar** [comment]
Well, the only instance I can find that uses user.change_password is the need_password_change checker, so if we change that to profile, could we just throw up an alert telling users to change their password?

**Comment by Wingar** [comment]
Well, I've pushed up the change anyway, just moves to profile and alerts the user. Can't be worse than broken, right?

**Comment by walkeriniraq** [comment]
Ship it!

**Comment by walkeriniraq** [comment]
Annoying but not harmful. Very nice.
