### ISSUE TITLE
photo popup stops working

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#217]
OK, here I think is the reproducible steps:
1) tweet to (at)yourself (or another user you control) that has a photo
2) go to your alerts page
3) click on the the photo in the 'tweets mentions' section.

from now on, you can't view any photos, even on the normal tweet stream.  In order to get the behavior back, you have to refresh the page from the browser.

Doubt this is useful, but this is the error in the JS console:

     Uncaught TypeError: undefined is not a functionapplication-73d875a84328d516b9ed63a5fc142074.js:20 (anonymous function)application-73d875a84328d516b9ed63a5fc142074.js:10 S.getapplication-73d875a84328d516b9ed63a5fc142074.js:11 fapplication-73d875a84328d516b9ed63a5fc142074.js:15 c.valueFnapplication-73d875a84328d516b9ed63a5fc142074.js:11 n.valueapplication-73d875a84328d516b9ed63a5fc142074.js:11 tapplication-73d875a84328d516b9ed63a5fc142074.js:11 a.valueFnapplication-73d875a84328d516b9ed63a5fc142074.js:11 n.valueapplication-73d875a84328d516b9ed63a5fc142074.js:9 (anonymous function)application-73d875a84328d516b9ed63a5fc142074.js:9 lapplication-73d875a84328d516b9ed63a5fc142074.js:22 Ember.TEMPLATES.photo_view.Ember.Handlebars.template.mainapplication-73d875a84328d516b9ed63a5fc142074.js:6 iapplication-73d875a84328d516b9ed63a5fc142074.js:16 ut.extend.renderapplication-73d875a84328d516b9ed63a5fc142074.js:15 u.createElementapplication-73d875a84328d516b9ed63a5fc142074.js:9 napplication-73d875a84328d516b9ed63a5fc142074.js:16 v.ensureChildrenAreInDOMapplication-73d875a84328d516b9ed63a5fc142074.js:16 _.extend._ensureChildrenAreInDOMapplication-73d875a84328d516b9ed63a5fc142074.js:7 r.invokeapplication-73d875a84328d516b9ed63a5fc142074.js:7 r.flushapplication-73d875a84328d516b9ed63a5fc142074.js:7 n.flushapplication-73d875a84328d516b9ed63a5fc142074.js:7 s.endapplication-73d875a84328d516b9ed63a5fc142074.js:7 s.runapplication-73d875a84328d516b9ed63a5fc142074.js:11 uapplication-73d875a84328d516b9ed63a5fc142074.js:11 v.registeredActions.(anonymous function).handlerapplication-73d875a84328d516b9ed63a5fc142074.js:15 (anonymous function)application-73d875a84328d516b9ed63a5fc142074.js:2 it.event.dispatchapplication-73d875a84328d516b9ed63a5fc142074.js:2 v.handle

**Comment by Wingar** [comment]
Yep, certainly reproducible. Should it link to the actual tweet page like the rest of tweets in alerts instead of fixing up the modal? Seems like a quicker fix.

**Comment by tasermonkey** [comment]
Best: it works exactly how it works on the main tweets page
Though what you said it's reasonable.
