### ISSUE TITLE
API for POSTing photos for twitarr timeline

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#219]
As far as I can tell by https://github.com/walkeriniraq/twitarr/blob/master/rest_documentation.md#rest-documentation and the config/routes.rb, there is a way to POST the user's avatar, but there is no way to POST images for the twitarr timeline.

**Comment by tasermonkey** [comment]
That actually may be true... As at the time I didn't know how to do that.  Like I don't know how to accept the metadata and the image data at the same time.

**Comment by RangerRick** [comment]
Ah, I didn't know it needed to accept any metadata.  If I post raw image data with params=key=XXX it would know what user to associate it with, right, and I could get an ID back?  And then I post the twitarr message referencing that ID next...

**Comment by tasermonkey** [comment]
Thats what I plan on doing now :-)

**Comment by RangerRick** [comment]
Awesome, thanks!

**Comment by walkeriniraq** [comment]
From what I understand there's no CruiseMonkey this year, so there's not a huge reason for this to exist any more.
