### ISSUE TITLE
User vCards

### ISSUE THREAD

**Issue by Wingar** [walkeriniraq/twitarr#223]
Not that kind, you gutterbrain, you

But right now the vCard standard is the only way to get some contact information into a users phone. (Damnit, W3C), and think about it, last time I was on the cruise people always seemed to have some kind of trouble with getting a persons contact info. We already have a lot of info (and we can easily add more), why not have a single button to save that contact info?

It's not the prettiest standard but it's easy and well supported.

**Comment by walkeriniraq** [comment]
Your ideas are intriguing to me and I wish to subscribe to your newsletter.

**Comment by tasermonkey** [comment]
sounds like a good idea to me.  But might have an option for people to "Opt out" (or in) within their profile.

**Comment by Wingar** [comment]
Good idea!

**Comment by tasermonkey** [comment]
Just playing with the ruby api via IRB... ruby makes this relatively easy thanks to a lib named 'vcard'.  :-)  Though I assume you are already well on your way to finishing it since its been self assigned, I was just curious on the format of it.

**Comment by Wingar** [comment]
Protip, look into Pry, so much better than just irb

**Comment by tasermonkey** [comment]
I have pry install, I just never remember to use it :-)  I don't use ruby in my day job.
