### ISSUE TITLE
JoCoTel

### ISSUE THREAD

**Issue by Wingar** [walkeriniraq/twitarr#226]
Real important issue!

Who's here and what room no :)

**Comment by Wingar** [comment]
Oh, and at the Embassy, 832

**Comment by tasermonkey** [comment]
I was going to walk down to jocotel.  We were trying to figure out if people are up yet.

**Comment by Wingar** [comment]
People are certainly up. Atrium is packed.

**Comment by walkeriniraq** [comment]
We're coming in tomorrow. See you guys on the boat!

**Comment by tasermonkey** [comment]
Made it here.  Doesn't seem packed now.

**Comment by Wingar** [comment]
Well, I think everyone's had breakfast and stuff now. Im just up in my room trying to sort out my SIM card.

**Comment by tasermonkey** [comment]
We are playing love letter in the atrium.
