### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Wingar** [walkeriniraq/twitarr#227]
Listing of JCC events with agenda and calendar view. 
Includes CSV export and simple print view (for helper desk).
Users can create their own events, and events can have user signups. (Eg, "Need 5 for D&D", users can register themselves for the event on the event page)

**Comment by tasermonkey** [comment]
Alsi I would say, export to iCal for iPhone / Android users

**Comment by Wingar** [comment]
Added a new API controller for events as well as other goodies related to it in  d79851df4f08a8bf5143cf0e709f8a5a37a97bec

**Comment by Wingar** [comment]
I've been working on events a lot lately, and while it's fresh in my mind I've written up a list of goals/features/etc in a bit of a documentation form. 

On the events index page, there are 3 main sections, the first is the the main list of events. It will show 20 per page, have events separated into different days and will be only show events that are still upcoming.
The next is the past events, this will simply show all events that have passed in time, ordered from most recent to least. 
The third is upcoming events. This shows events that the user has signed up for or favourited ordered from soonest to latest.

On the event detail page users can sign up for events, favourite them, see who else has signed up, etcetera. Additionally, if the user is the user that created the event they can edit (Currently not implemented. On top of priorities) or delete the event, on editing they can change every detail except the title which is fixed. 
If a user signs up for an event or favourites one, they will be sent an alert half an hour before the event starts (Currently not implemented)

Events are also searchable in the main search section of the site. (Currently not implemented but won't be hard). Should only show events that have not started yet (Or haven't ended.)

Additional features currently not implemented, but will be if I can find the time:
Export event as iCal format so users can add  to their own phone/pc/etc calendar. (Implemented but not exposed to the user yet)
Export all events as CSV format (Implemented but not exposed to the user yet, it's mostly for Home Office to use)
Export all favourited/signed up for events as CSV format.
