### ISSUE TITLE
Pagination on forum thread views

### ISSUE THREAD

**Issue by Wingar** [walkeriniraq/twitarr#229]
Does what it says on the box. Threads get sluggish on phones after about 20 posts.

**Comment by tasermonkey** [comment]
Also on the forum list itself too.

**Comment by Wingar** [comment]
Almost finished, forum index just need to link to page of last unread post instead of the first page.

**Comment by Wingar** [comment]
Also a proper pagination bar would be nice, with individual page numbers.

**Comment by Wingar** [comment]
Oh, and to update the new Forum.last_post_time variable, just run this in Rails Console or wherever
```Forum.each { |x| x.last_post_time = x.last_post; x.save }```

**Comment by Wingar** [comment]
Oh. I haven't even looked at the API endpoinds either. those are probably not updated.

**Comment by Wingar** [comment]
Okay, looks like the only thing that's really left (Ignoring the full page-number-pagination) is have the link go to the page of the latest post. That shouldn't be hard.

**Comment by Wingar** [comment]
Actually, nevermind. It's already in place, simple! Closing issue.
