### ISSUE TITLE
Service Discovery for CruiseMonkey

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#243]
Multiple people(developers) suggested some sort of service discovery for CruiseMonkey to find the twitarr server.

Their suggestions included: 
mDNS 
or using some hand written "Multicast" method

See https://github.com/RangerRick/CruiseMonkey/issues/44 for that side of the issue.

@joey mentioned that he was interested in looking into this.

**Comment by Wingar** [comment]
I've been looking into this a fair bit. I  think custom multicast is still the way to go, but there's nothing stopping us from running mDNS on the side, the VM already has avahi on it. 
mDNS as a whole unfortunately is a no-go for general distribution (Cruisemonkey? Maybe). It only seems to be a thing by default on OS X and I think that means iOS but I'm not sure. If its on iOS I think we should use it for those people, but fallback on ship DNS for everyone else.

**Comment by joey** [comment]
I can test with my Mac and iOS devices on FotS in May.

**Comment by Wingar** [comment]
I just added a first implementation of a simple server for multicast discovery. It's fairly simple (But messy and should probably be re-written. It's just bad code), and frankly I haven't tested with jruby, only MRI. But it works. There's also a test implementation for a client. It's not a good one, but it's something to reference from.

The protocol is pretty simple. Generate some kind of UUID that's 32 characters long, ping off a multicast with that on UDP port 30512 (can obviously change), and start listening on the same port for a reply.
Reply format is plaintext CSV, the format is
"ack,[UUID you sent off],[Twitarr address]"
The twitarr address isn't strict, it can even give a DNS entry. It's just a string.

The reason I decided to go with UUIDs is later down we might want encode some information into those UUIDs, maybe have some device specific replies, or maybe just analytics. I dunno, it's left open for anything.

Feel free to tear it apart and make it not terrible, but it's something to start with.

**Comment by RangerRick** [comment]
My only concern is whether RCI routes multicast on the ship.  I'd bet they block mDNS since it's common to do so...  I don't recall seeing other people's laptop shares showing up on my mac when I got on the wireless.

**Comment by tasermonkey** [comment]
yeah, I think when @joey goes on the FotS in may he can find out for sure, but if I am a betting man, it would be blocked.

**Comment by RangerRick** [comment]
I had Scarface talk to RCI IT and yeah, they don't support multicast.  :(  I think mDNS makes it for your local AP (I remember seeing some other computers showing up on my laptop) but I bet it doesn't get routed across the whole ship.  We'll have to stick to manual config I guess.
