### ISSUE TITLE
Coloring of 'new' on the forums

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#245]
Finding forums with new posts in it is hard.  Lets add some color to it or do something else to help contrast forums that have new posts in them.

**Comment by Wingar** [comment]
i just noticed the line
```ret[:new_posts] = pluralize(count, '<b class="highlight">new</b> post')  if count > 0```
So... it runs pluralize, which just concatenates and adds an S on, if the count is already high enough to be plural? That seems... wasteful.
