### ISSUE TITLE
Keeping track of who one's met

### ISSUE THREAD

**Issue by tasermonkey** [walkeriniraq/twitarr#257]
"Is there a way to take notes in the Cruise Monkey App -- some way to keep track of who one's met? Maybe something like those 3DS games that allow you to pick up the avatar of other people nearby, but actually linked to real pictures/names. Opt-in, of course, for privacy." - http://www.jonathancoulton.com/forums/index.php?p=/discussion/2405/joco-cruise-5-post-mortem-feedback-thread

Though I don't think we need it to be like automatic from people nearby, but instead maybe have the user be able to "star" other users manually, and maybe make some personal notes on them?

**Comment by Wingar** [comment]
So I started working on this and, well... I'm just gonna attach a screenshot of a story I posted in slack about this. I'll probably have this done fairly soon.
![chrome_2016-01-27_22-52-50](https://cloud.githubusercontent.com/assets/1838015/12612702/ced8b5a8-c548-11e5-8f2a-2de6b93a2d96.png)
