### ISSUE TITLE
500 error loading forums

### ISSUE THREAD

**Issue by RangerRick** [walkeriniraq/twitarr#266]
On a fresh install, I get this error after logging in as 'admin' and going to the forums:

```
Started GET "/forums/thread/5626e715aaebbc864a000004/0" for 127.0.0.1 at 2015-10-24 15:30:44 -0400
Processing by ForumsController#show as JSON
  Parameters: {"id"=>"5626e715aaebbc864a000004", "page"=>"0"}
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 2.0000ms
  MOPED: 127.0.0.1:27017 QUERY        database=development collection=forums selector={"_id"=>BSON::ObjectId('5626e715aaebbc864a000004')} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 8.0000ms
  MOPED: 127.0.0.1:27017 QUERY        database=development collection=users selector={"$query"=>{"un"=>"admin"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 3.0000ms
  MOPED: 127.0.0.1:27017 QUERY        database=development collection=photo_metadata selector={"_id"=>BSON::ObjectId('54b968dbaaebbcf93b00002b')} flags=[] limit=0 skip=0 batch_size=nil fields=nil runtime: 2.0000ms
Completed 500 Internal Server Error in 51ms

NameError (undefined local variable or method `location' for #<ForumPostDecorator:0x1fc66cdb>):
  app/decorators/forum_post_decorator.rb:5:in `to_hash'
  app/decorators/forum_decorator.rb:44:in `to_hash'
  app/decorators/forum_decorator.rb:41:in `to_hash'
  app/controllers/forums_controller.rb:31:in `show'
```

**Comment by martinbogo** [comment]
Location is not fully implemented in the forum decorator... we should (temporarily) disable locations by commenting out location:

app/decorators/forum_post_decorator.rb

lass ForumPostDecorator < BaseDecorator
  delegate_all

  def to_hash(last_view = nil)
    ret = {
        id: id.to_s,
        author: author,
        display_name: User.display_name_from_username(author),
        text: clean_text_with_cr(text),
        timestamp: timestamp,
        likes: likes,
        likes_counts: likes.length,
        photos: decorate_photos,
        hash_tags: hash_tags,
#        location: location,
        mentions: mentions
    }
    ret[:new] = (timestamp > last_view) unless last_view.nil?
    ret
  end

  def decorate_photos
    return [] unless photos
    photos.map { |x| { id: x, animated: !x.blank? && PhotoMetadata.find(x).animated } }
  end

end

**Comment by Wingar** [comment]
Commenting it out seems to be the best thing for now. I can't even remember why that's there.

**Comment by RangerRick** [comment]
Ah yeah, that got fixed with the merges last night.  Closing.
